#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm run lint && npx --no-install commitlint --edit "$1"
# [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]
# feat: feat desc
npx --no-install commitlint --edit "$1"